name: Release

on:
  push:
    branches: [ dev ]
  workflow_dispatch:
    inputs:
      build_all:
        description: 'Build all modules'
        required: false
        default: false
        type: boolean
      nodos_sdk_version:
        description: 'Nodos SDK Version'
        required: false
        default: ''
        type: string
      clean:
        description: 'Clean build'
        required: false
        default: false
        type: boolean

jobs:
  set-build-number:
    name: Set Build Number
    runs-on: self-hosted
    outputs:
      build_number: ${{ steps.offset-build-number.outputs.build_number }}
    steps:
      - name: Set build number with offset
        id: offset-build-number
        run: echo "::set-output name=build_number::$(( ${{ github.run_number }} + 451 ))"

  call-release-modules:
    name: Release Modules
    needs: set-build-number
    uses: nodos-dev/actions/.github/workflows/release-modules.yml@main
    with:
      ref_name: ${{ github.ref_name }}
      build_all: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.build_all || 'false' }}
      nodos_sdk_version: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.nodos_sdk_version || '' }}
      clean: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.clean || 'false' }}
      build_number: ${{ needs.set-build-number.outputs.build_number }}
