name: Release

on:
  push:
    branches: [ dev ]
  workflow_dispatch:
    inputs:
      build_all:
        description: 'Build all modules'
        required: false
        default: false
        type: boolean
      nodos_sdk_version:
        description: 'Nodos SDK Version'
        required: false
        default: ''
        type: string
      clean:
        description: 'Clean build'
        required: false
        default: false
        type: boolean

jobs:
  set-build-number:
    name: Set Build Number
    runs-on: self-hosted
    outputs:
      build_number: ${{ steps.offset-build-number.outputs.build_number }}
    steps:
      - name: Offset Build Number
        id: offset-build-number
        shell: bash
        run: |
          set BUILD_NUMBER=$(( ${{ github.run_number }} + 451 ))
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT

  call-release-modules-wd:
    name: Release Modules
    needs: set-build-number
    uses: nodos-dev/actions/.github/workflows/release-modules.yml@main
    if: ${{ github.event_name == 'workflow_dispatch' }}
    with:
      ref_name: ${{ github.ref_name }}
      build_all: ${{ github.event.inputs.build_all }}
      nodos_sdk_version: ${{ github.event.inputs.nodos_sdk_version }}
      clean: ${{ github.event.inputs.clean }}
      build_number: ${{ needs.set-build-number.outputs.build_number }}
  
  call-release-modules-push:
    name: Release Modules
    needs: set-build-number
    uses: nodos-dev/actions/.github/workflows/release-modules.yml@main
    if: ${{ github.event_name == 'push' }}
    with:
      ref_name: ${{ github.ref_name }}
      build_all: false
      nodos_sdk_version: ""
      clean: false
      build_number: ${{ needs.set-build-number.outputs.build_number }}
